-- Fictional test data
INSERT INTO destination (name, country, description, high_season_months) VALUES
  ('Copenhagen', 'Denmark', 'Harbour city of design, food and royal history.', '6,7,8,12'),
  ('Rome', 'Italy', 'The eternal city – ancient history, art and trattorias.', '4,5,6,7,9,10');

INSERT INTO product_type (code, name, group_form, flexibility, personalisation, price_principle, booking_form, included, not_included) VALUES
  ('public', 'Public small-group tour', 'Shared with other travellers, max 12 people', 'Fixed date, time and route', 'None – same tour for everyone', 'Fixed price per person', 'Instant online booking', 'Licensed local guide; walking route; small group', 'Entrance fees; food and drinks; transport'),
  ('private', 'Private tour', 'Only your own party', 'You choose date and start time; pace adapted on the day', 'Route and focus adapted to your interests', 'Fixed price per group, depends on size', 'Request – confirmed by Amitylux within 24 hours', 'Private guide; adapted route; skip-the-line where possible', 'Entrance fees unless agreed; meals; hotel pick-up'),
  ('customised', 'Customised experience', 'Your party, any size', 'Fully flexible – half day to several days', 'Designed from scratch with an Amitylux planner', 'Price on request after dialogue', 'Structured request followed by personal dialogue', 'Personal planner; matched guide; combined services (transport, food, boats, special access)', 'Flights and hotels; items not in the final proposal');

INSERT INTO experience (destination_id, type_code, title, description, price_per_person, price_level, languages, interests, min_group, max_group, duration_hours, included, not_included, value_points, guide_name, guide_expertise, rating, review_count, review_quote, sustainable_label, off_the_beaten_track) VALUES
  (1, 'public', 'Copenhagen Old Town Walk', 'The classic walk through Nyhavn, Amalienborg and the medieval centre.', 45, 'low', 'English,Danish', 'history,architecture', 1, 12, 2.5, 'Guide; route map', 'Entrance fees; drinks', 'Small group;Local expertise', 'Mette', 'Historian, 12 years guiding', 4.8, 312, '"Mette made 900 years of history feel alive."', 'Walking', 0),
  (1, 'public', 'Nordic Food Walk', 'Tastings at five local producers in Vesterbro.', 89, 'medium', 'English', 'food', 1, 10, 3, 'Guide; 5 tastings', 'Extra drinks', 'Small group;Local expertise;Special access', 'Jonas', 'Former chef', 4.9, 188, '"Best food tour we have ever taken."', 'Walking', 1),
  (1, 'private', 'Private Royal Copenhagen', 'Your own guide through palaces and the crown jewels – at your pace.', 160, 'high', 'English,Danish,German,Spanish', 'history,art,architecture', 1, 8, 4, 'Private guide; tickets for Rosenborg', 'Meals; transport', 'Flexibility;Local expertise;Time saved;Safety', 'Sofie', 'Art historian', 4.9, 96, '"Felt like visiting with a friend who knows everything."', NULL, 0),
  (1, 'private', 'Private Harbour & Design by Bike', 'Cycle the new harbour districts and design icons.', 120, 'medium', 'English,Danish', 'architecture,nature,hidden gems', 1, 8, 3, 'Private guide; bikes and helmets', 'Food', 'Flexibility;Local expertise', 'Anders', 'Architect', 4.7, 54, '"Perfect for our family – kids loved it."', 'Bike', 1),
  (1, 'customised', 'Tailor-made Copenhagen Day', 'A day designed around your party: culture, food, boats and more.', NULL, 'premium', 'English,Danish,German,Spanish,French', 'history,art,food,architecture,nature,hidden gems', 1, 40, 8, 'Planner; matched guide; combined services', 'Flights and hotels', 'Personal planner;Special access;Flexibility;Time saved', 'Amitylux planning team', 'Local experts across fields', 5.0, 21, '"They thought of everything."', NULL, 0),
  (2, 'public', 'Colosseum & Forum Small Group', 'Skip-the-line tour of ancient Rome.', 69, 'medium', 'English,Italian,Spanish', 'history,architecture', 1, 12, 3, 'Guide; skip-the-line tickets', 'Food; transport', 'Small group;Special access', 'Giulia', 'Archaeologist', 4.8, 540, '"Giulia answered every question."', 'Walking', 0),
  (2, 'public', 'Trastevere Evening Food Tour', 'Supplì, pizza and gelato in Rome''s most charming quarter.', 79, 'medium', 'English', 'food,nightlife', 1, 12, 3.5, 'Guide; dinner-sized tastings; wine', 'Extra drinks', 'Small group;Local expertise', 'Marco', 'Food writer', 4.9, 402, '"We did not need dinner afterwards!"', 'Walking', 1),
  (2, 'private', 'Private Vatican Early Entry', 'Enter the Vatican Museums before the crowds with your own guide.', 210, 'premium', 'English,Italian,German,French,Spanish', 'art,history', 1, 8, 3.5, 'Private guide; early entry tickets', 'Hotel transfer', 'Special access;Time saved;Flexibility;Safety', 'Elena', 'Art historian, Vatican licensed', 4.9, 133, '"Sistine Chapel almost to ourselves."', NULL, 0),
  (2, 'private', 'Appian Way by E-bike', 'Ancient road, aqueducts and catacombs away from the centre.', 115, 'medium', 'English,Italian', 'history,nature,hidden gems', 1, 8, 4, 'Private guide; e-bikes', 'Catacomb ticket', 'Flexibility;Fewer crowds', 'Luca', 'Cycling guide', 4.8, 77, '"A side of Rome we never knew."', 'Bike', 1),
  (2, 'customised', 'Tailor-made Roman Holiday', 'Multi-day programme with private guides, cooking class and transport.', NULL, 'premium', 'English,Italian,German,Spanish,French,Danish', 'history,art,food,architecture,nature,nightlife,hidden gems', 1, 40, 16, 'Planner; matched guides; combined services', 'Flights and hotels', 'Personal planner;Special access;Flexibility;Time saved', 'Amitylux planning team', 'Local experts across fields', 4.9, 17, '"Our best family holiday ever."', NULL, 0);

INSERT INTO addon (code, name, description, price_hint, interest) VALUES
  ('guide_language', 'Guide in your language', 'A guide speaking your preferred language', 'Included for private', NULL),
  ('museum', 'Museum or cultural visit', 'Tickets and guiding at a museum or site', 'From €25 pp', 'art'),
  ('food', 'Food experience', 'Tasting, cooking class or restaurant booking', 'From €60 pp', 'food'),
  ('transport', 'Private transport', 'Car or minivan with driver', 'From €180 per half day', NULL),
  ('boat', 'Boat or harbour trip', 'Private boat on the harbour / river', 'From €300 per boat', 'nature'),
  ('activity', 'Other activity', 'Bike, kayak, workshop or similar', 'On request', 'hidden gems');

INSERT INTO inquiry (reference, created_at, status, contact_name, contact_email, destination_id, experience_id, date_from, date_to, group_type, group_size, interests, language, pace, budget, addons, guide_language, guide_focus, guide_style, notes, recommended_type) VALUES
  ('AMX-1001', '2026-09-20 10:12:00', 'IN_PROGRESS', 'Laura Schmidt', 'laura@example.com', 1, 5, '2026-10-14', '2026-10-15', 'family', 5, 'history,food', 'German', 'relaxed', 'high', 'food,boat', 'German', 'Royal history', 'Relaxed and child friendly', 'Two children aged 7 and 10.', 'customised'),
  ('AMX-1002', '2026-09-26 18:40:00', 'NEW', 'James Carter', 'james@example.com', 2, 8, '2026-11-03', '2026-11-03', 'couple', 2, 'art,history', 'English', 'flexible', 'premium', 'museum', 'English', 'Renaissance art', 'Storyteller', 'Anniversary trip.', 'private');
